# Exercises with Python




https://docs.python.org/

https://docs.scipy.org/doc/numpy/




In [1]:
import numpy as np

## Numpy
### Exercise 1
#### Creat an array of 450 random integers between -10 and 10

https://docs.scipy.org/doc/numpy-1.15.1/reference/generated/numpy.random.randint.html

In [3]:
array = np.random.randint(low=-10, high=10, size=450, dtype='int')

array

array([ -6,  -8,   0,  -9,   5,   3,   8,  -6,   8,  -5,  -7,  -8,   2,
        -6,  -5,  -3,  -7,  -5,  -6, -10,   4,  -2,   4,  -8,   5,  -5,
         4, -10,  -7,   3,   9,   1,   7,  -2,  -7,   7,   8,   2,   3,
         9,   5,   3,   0,  -5,   7,   7,  -4,  -1,   4,   6,   9,  -9,
        -4,  -3, -10,   6, -10,  -9,   0,   4,  -7,   9,  -7,  -3,   6,
        -8,  -7,  -1,   9,  -2,  -7, -10,   5,   6,  -7,   7,  -1,  -9,
         8,  -6,  -8,   8,   0,  -8,   8,  -3,  -2,   4,  -5,   3,   9,
         4,  -8,  -9,  -1, -10,   5,  -9,   8,  -7,   0,   7, -10, -10,
        -1,   7,   7,   1,  -2,  -3,  -9,  -1,  -4,   2,   9,  -1,   9,
         3,  -9,   9,  -7,   3,   4,  -3,   6, -10,   9,   9,  -2,  -7,
         4,  -6,  -4, -10,  -4,  -7,   8,  -4,  -5,  -2,  -8,   6,   9,
         4,   4,  -4,  -1,  -7,  -2,  -3,  -2,   0,  -2,   3, -10,  -2,
         7,  -1,   9,  -8,  -1,   7,  -9,   0,  -3,   2,  -9,  -2,  -7,
        -6,   8,  -9,   8,  -3,  -1,  -6,  -1,  -5,   8,  -3,   

#### Resize it as a 5x70 matrix Is there a problem? If there is, correct it.

We check what dimension our array has:

In [3]:
array.shape

(450,)

We resize:

In [4]:
matrix = array.reshape(5,70)

ValueError: cannot reshape array of size 450 into shape (5,70)

In [5]:
matrix = array.reshape(5,90)
matrix

array([[ -3,   1,  -7,  -8,   4,   2,   0,   6, -10,   4,   3, -10,   6,
          5,  -9,  -4,   8,   7,  -9,   2,   9,  -2,  -9,   5, -10,   7,
         -2,   3,  -1,   4,  -5,   9,  -5,   0,   7,   9,   7,  -3,   1,
          2,  -6,  -6,   3,  -9,  -3,   2,  -4,  -8,   0,  -4,  -6,   7,
         -7,   3,  -3,   2,  -1,  -7,  -4,  -4,   4,   1,  -3,  -6,  -4,
          4,  -4,  -1,   2,  -3,  -4,   9,  -5,   0,   6,  -2,  -3,   0,
         -8,   0,  -2,  -5,  -8,   5, -10,   0,   0,  -2,  -7,  -6],
       [ -7,   3,   8,   3,   8,   7,  -3,   0,  -9,   6, -10,  -5,   2,
          1,   5,  -8,  -8,   5,   3,   0,  -8,   5,  -4,   1,   8, -10,
          3,   7,   6,   9,  -4, -10,   7, -10,   0,   6,  -2,   0,   4,
          6,  -6,  -3,   2,   5,  -8,   8,   1,   8,  -6,   6,   7,  -3,
          7,  -3,  -8,  -6,  -1, -10,  -2,  -6,   3,  -2,   4,  -4,  -6,
         -4,   3,   1,   6,   8,  -9,   3,   8,   6,   6,  -6,  -2,   5,
         -5,   6,   1,  -4,  -5,   8,  -2,   3,   9,  -

In [6]:
matrix.shape

(5, 90)

#### Get the positive numbers from that matrix using boolean indexing

In [7]:
matrix>0

array([[False,  True, False, False,  True,  True, False,  True, False,
         True,  True, False,  True,  True, False, False,  True,  True,
        False,  True,  True, False, False,  True, False,  True, False,
         True, False,  True, False,  True, False, False,  True,  True,
         True, False,  True,  True, False, False,  True, False, False,
         True, False, False, False, False, False,  True, False,  True,
        False,  True, False, False, False, False,  True,  True, False,
        False, False,  True, False, False,  True, False, False,  True,
        False, False,  True, False, False, False, False, False, False,
        False, False,  True, False, False, False, False, False, False],
       [False,  True,  True,  True,  True,  True, False, False, False,
         True, False, False,  True,  True,  True, False, False,  True,
         True, False, False,  True, False,  True,  True, False,  True,
         True,  True,  True, False, False,  True, False, False,  True,
     

In [40]:
matrix[matrix>0]

array([5, 9, 4, 3, 2, 2, 3, 2, 3, 8, 1, 7, 7, 3, 9, 1, 3, 1, 4, 4, 6, 8,
       9, 1, 8, 1, 7, 9, 3, 8, 7, 8, 1, 3, 5, 7, 1, 6, 6, 5, 5, 5, 9, 5,
       1, 5, 6, 3, 2, 2, 5, 2, 2, 8, 4, 3, 7, 6, 5, 7, 2, 3, 2, 1, 5, 3,
       9, 7, 7, 6, 2, 6, 3, 9, 1, 4, 8, 1, 5, 8, 4, 9, 4, 7, 9, 9, 3, 1,
       7, 3, 8, 4, 1, 6, 4, 4, 1, 7, 4, 8, 5, 4, 9, 9, 3, 1, 8, 7, 3, 5,
       4, 4, 7, 7, 9, 1, 7, 7, 9, 5, 2, 7, 3, 7, 1, 8, 1, 7, 5, 1, 7, 5,
       9, 8, 3, 7, 3, 1, 2, 2, 3, 8, 3, 3, 5, 1, 1, 5, 5, 3, 8, 7, 4, 2,
       6, 1, 7, 8, 6, 5, 1, 5, 1, 2, 1, 4, 7, 3, 8, 3, 1, 1, 5, 9, 7, 1,
       1, 2, 8, 8, 2, 2, 2, 9, 6])

#### Obtain with a function the non-duplicated data

In [8]:
# Example of set
L = [1,1,2]
type(L)

list

In [42]:
set(L)

{1, 2}

In [9]:
# transformation back to list
L = list(set(L))
L

[1, 2]

In [4]:
# array -> list -> set
array = list(array)
array = set(array)

array

{-10, -9, -8, -7, -6, -5, -4, -3, -2, -1, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9}

In [11]:
# set -> list -> array
array = list(array)
array = np.array(array)

array

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  -6, -10,  -9,
        -8,  -7,  -2,  -5,  -4,  -3,  -1])

In a line of code:

In [10]:
no_duplicados = np.array(list(set(array)))
no_duplicados

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1])

#### On the non-duplicated data, obtain the mean and quartiles.

In [11]:
# we use the mean function
np.mean(no_duplicados)

-0.5

In [12]:
# percentiles
np.percentile(no_duplicados, 25)

-5.25

#### For this array of non-duplicated elements, add a unit to each element.

In [14]:
x = np.array([-5,6,-7,9])
print(np.absolute(x)) #Abs

[5 6 7 9]


#### Create a diagonal matrix

In [15]:
a = np.diag(np.arange(3))
a

array([[0, 0, 0],
       [0, 1, 0],
       [0, 0, 2]])

In [17]:
np.zeros((3,5),dtype=float)

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

Equally divide into n spaces

In [41]:
x = np.linspace(1,2,5)
x

array([1.  , 1.25, 1.5 , 1.75, 2.  ])